# 采用toml文件格式
# https://github.com/BurntSushi/toml

# grpc.trongrid.io:50051 主节点 本身是负载均衡的
# 3.225.171.164:50051 其他主节点 https://cn.developers.tron.network/docs/官方公共节点
# grpc.shasta.trongrid.io:50051 测试节点
[client]
nodeTrx="grpc.shasta.trongrid.io:50051" # fullnode 主节点
nodeUrl=[] # fullnode 其他节点
main_addr="TDRPyn57F4riYTJFcHaQbrzgFaGe8HSumL" #主钱包地址
password="1070fcd0-ed20-425d-af1f-6d217d2e4820" #主钱包秘钥加密前的密码 uuid
key_store="/home/user/tron/key_store" #用户秘钥保存路径 从运行文件路径开始算 默认 key_store
db_addr="/home/user/tron/trx.db"
port="9291"
logLevel="info" # 日志等级默认
count=20 #批量查询交易记录个数
feelimit=5000000 # 每次转账trc20合约燃烧的能量 单位sun 默认5trx
perfee=3 # 每次归集每个合约需要手续费消耗
minfee=3 # 每个地址至少保留多少trx手续费

# 合约配置
[[contract]]
name="USDT"  # 暂时没有用到
type="trc20" # 合约类型
contract="TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t" # trc20 合约地址
issuer="THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC" # 发行者地址 暂时没有用到
port="9292" # 监听端口
min_amount=0.1 # 最小归集数量

[[contract]]
name="BTT"
type="trc10" # 合约类型
contract="1002000" # 合约配置 trc10 合约ID assertname
issuer="TF5Bn4cJCT6GVeUgyCN4rBhDg42KBrpAjg" # 发行者地址 暂时没有用到
port="9293" # 监听端口
min_amount=0.1 # 最小归集数量

[collection]
time_interval_min=60 # 归集检测间隔  单位 分
min_amount=1 # trx最小归集钱包余额 单位TRX 后面 6个零 1TRX =10^6SUN

[scantraderecord]
time_interval_sec=60 # 扫描交易记录检测间隔 单位秒
# 扫描交易记录起始位置 如果配置为正数 取最大值开始扫描
# 如果为负数 则取绝对值 从绝对值位置开始扫描，不取最大值开始扫描
min_scan_block = 121000
goroutine_num=4 # 每次扫描开的协程数量 每个协程扫描能一次扫描100个块 是很快的 tron 3秒更新一次块 完全很快就追上了


# 3.225.171.164:50051 
# 52.53.189.99:50051 
# 18.196.99.16:50051 
# 34.253.187.192:50051 
# 52.56.56.149:50051 
# 35.180.51.163:50051 
# 54.252.224.209:50051 
# 18.228.15.36:50051 
# 52.15.93.92:50051 
# 34.220.77.106:50051 
# 13.127.47.162:50051 
# 13.124.62.58:50051 
# 35.182.229.162:50051 
# 18.209.42.127:50051 
# 3.218.137.187:50051 
# 34.237.210.82:50051 
